### ISSUE TITLE
Figure out how to work with an unpatched MPFR build

### ISSUE THREAD

**Issue by copumpkin** [ekmett/rounded#13]
This is mostly a placeholder issue for ideas on how to move away from the current hackish design. 

We have an open ticket at the MPFR tracker here and it describes some of the issues and what we've done to deal with them: https://gforge.inria.fr/tracker/index.php?func=detail&aid=17185&group_id=136&atid=622

At some point I'll write up a more complete description of the issues at play.

**Comment by claudeha** [comment]
fixed by https://github.com/ekmett/rounded/pull/27 merge

(no longer an issue, as recent GHC integer-gmp no longer uses a custom allocator)
