### ISSUE TITLE
Documentation of rounding modes

### ISSUE THREAD

**Issue by dmcclean** [ekmett/rounded#14]
```
data RoundingMode
  = TowardNearestWithTiesAwayFromZero
  | TowardNearest
  | TowardZero
  | TowardInf
  | TowardNegInf
  | AwayFromZero
  | Faithfully
  deriving (Eq,Ord,Show,Read,Data,Typeable)
```

I have a few questions.
1. What does "Faithfully" mean? Google lead me around in circles and I couldn't figure it out.
2. If `TowardNearestWithTiesAwayFromZero` has to deal with ties, what does `TowardNearest` do with ties?
3. It seems (naively, I don't know anything about this) that any of the Toward... or AwayFrom... methods could be the one you wanted to use to resolve ties, which suggests jiggling constructors around?

**Comment by claudeha** [comment]
fixed in https://github.com/ekmett/rounded/pull/27 merge
