### ISSUE TITLE
Replace all the bindings with a straight MPFR binding for GHC 7.10

### ISSUE THREAD

**Issue by copumpkin** [ekmett/rounded#21]
All (or most?) of the GC-related shenanigans shouldn't be necessary anymore.

**Comment by claudeha** [comment]
I got straight bindings working with ghc-7.10 but am a bit concerned about performance - my attempt does a lot of allocaBytes and copyByteArray in case the ByteArray are moved by GC around the foreign calls.  So maybe CMM wrappers would still be beneficial to avoid this extra work, perhaps along the lines of http://lpaste.net/7271992395112120320

**Comment by claudeha** [comment]
fixed by https://github.com/ekmett/rounded/pull/27 merge
