### ISSUE TITLE
The Show instance is very slow

### ISSUE THREAD

**Issue by redneb** [ekmett/rounded#22]
Currently the `Show` instance uses `showFloat` from `Numeric` from `base`. Unfortunately, that function is rather slow when it comes to numbers with a large number of digits. For example, calculating the first 100,000 decimal digits of π (hence 100,001 significant decimal digits or 332197 significant binary digits) with the following:

```
length $ show (pi :: Rounded TowardZero 332197)
```

takes 6 seconds to complete in my system. On the other hand, if I use the `Show` instance of `Integer` to find the same digits, e.g. with

```
length $ show (truncate (pi * 10 ^ 100000 :: Rounded TowardZero 332197) :: Integer)
```

takes only 0.15 seconds to complete in the same system.

**Comment by redneb** [comment]
Just to clarify, I don't think we can improve the performance of `Show (Rounded r p)` by improving `showFloat` from `base`. `showFloat` is too general. I think an ad-hoc instance for `Rounded` is needed, just like how there is an ad-hoc instance for `Show Integer`. The latter is defined in `GHC.Show` and is super-optimized, so maybe it's a good idea to use it somehow.

**Comment by michalkonecny** [comment]
hmpfr has a Show instance based on mpfr_get_str and it is much faster than rounded's Show instance.  (See [Conversion.hs](https://code.google.com/p/hmpfr/source/browse/src/Data/Number/MPFR/Conversion.hs).) This binding was written by Aleš Bizjak long time ago.   I do not know how hard it is to make a similar binding in rounded.

**Comment by ekmett** [comment]
That definitely seems worth doing and doesn't look like a difficult port.

**Comment by claudeha** [comment]
fixed by https://github.com/ekmett/rounded/pull/27 merge
