### ISSUE TITLE
need a function to increase the precision of a mpfr number

### ISSUE THREAD

**Issue by michalkonecny** [ekmett/rounded#23]
I think it would be useful to have a function like:
`differentPrecision :: (Rounded m1 p1) -> (Rounded m2 p2)`

Rationale: It is sometimes wasteful to use the same very high precision in all sub-expressions of an expression.   I would like to calculate some sub-expressions using a lower precision and then combine it with higher precision calculations.  For example, when using interval Newton iterations, computing the first estimate can be usually done with a much lower precision than is required for the final result.  I think it would also be beneficial to increase precision during Newton iterations.

**Comment by ekmett** [comment]
Makes sense.

With 7.10, we can drastically simplify the internals of this package as we no longer need to try to bundle a custom, patched `mpfr`.

Consequently, I'll probably be spending some time cleaning this package up soon, and see if we can throw this in.

**Comment by claudeha** [comment]
fixed by https://github.com/ekmett/rounded/pull/27 merge

    Numeric.Rounded.precRound
      :: (Precision p2, Precision p1, Rounding r) =>
         Rounded r p1 -> Rounded r p2
