### ISSUE TITLE
What must be done for 7.10 compatibility?

### ISSUE THREAD

**Issue by davidsd** [ekmett/rounded#26]
I managed to get the 7.10 branch to compile with GHC 7.10.3 by making it compatible with the new integer-gmp, see here: https://github.com/davidsd/rounded/tree/7.10

However, even simple things like `fromInteger` don't seem to be working.  For example,

``` haskell
do
  let x :: Rounded AwayFromZero 128 = fromInteger 1
  print x
```

prints `2.584942247048919467950081e24`.  I guess this has something to do with the cmm wrappers, but I'm afraid I don't understand what they're doing or how they work. What can I do to get this working?

**Comment by claudeha** [comment]
fixed by https://github.com/ekmett/rounded/pull/27 merge
