### ISSUE TITLE
The 1.1 release is not in this repository

### ISSUE THREAD

**Issue by phadej** [ekmett/rounded#33]
https://hackage.haskell.org/package/rounded metadata points here.

**Comment by claudeha** [comment]
https://github.com/ekmett/rounded/releases/tag/rounded-1.1 https://github.com/ekmett/rounded/tree/v1.x

**Comment by phadej** [comment]
Is there a reason why `master` is not pointing there as well, or why `v1.x` isn't the default branch on GitHub?

This is slightly confusing setup.

**Comment by claudeha** [comment]
Ah, good point - I've updated `master`, not sure how to make `v1.x` default (I don't use github much).  Thanks for the report!

**Comment by phadej** [comment]
In Settings -> Branches you can select the default branch.

**Comment by claudeha** [comment]
Oh, I don't have permission on this repository, I guess @ekmett  would have to do that (set default branch of `rounded` to `v1.x`)...

**Comment by phadej** [comment]
Either way, also having `master` to track "latest vX.Y" branch would be fine for me (as a random contributor).
